name: OX Security Scan

# This is a basic workflow that is manually triggered

on:
  workflow_dispatch:
    # Inputs the workflow accepts.

  push:
    branches:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '**'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run OX Security Scan to check for vulnerabilities
        with:
          ox_api_key: ${{ secrets.OX_API_KEY }}
          ox_override_blocking: true
          ox_timeout: 20
          ox_fail_on_timeout: false
          ox_fail_on_error: false
        uses: oxsecurity/ox-security-scan@main
        
